### PR TITLE
Update EagerJoinQueryTrait.php

### PR DESCRIPTION
**Pull request by urusaich**
Fix a bug with aliases

### CODE REVIEW

**Comment by klimov-paul** [comment]
> Fix a bug with aliases

Which bug? Provide the code to reproduce it.

**Comment by urusaich** [comment]
```php
$query->eagerJoinWith('relationName AS alias');
```
builds query with
```sql
`relation_table_name`.*
```
not with
```sql
`alias`.*
```
select

**Comment by klimov-paul** [comment]
Provide a unit test for your issue.

**Comment by urusaich** [comment]
okay. a bit later

**Comment by urusaich** [comment]
done i think

**Comment by klimov-paul** [comment]
Resolved by commit a63d2a3598d6a7517fd81305b630cca2b856dec0

**Comment by klimov-paul** [comment]
Thank you

**Pull request closed without merging**
